{% set name = "sqsgenerator" %}
{% set version = "0.5.4" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/dgehringer/sqsgenerator/archive/v{{ version }}.tar.gz
  sha256: b76f396fc833186679c06f989d1ca5fda1ca87c5f860d34d50dc58805d6b3087


build:
  number: 0
  entry_points:
    - sqsgen = sqsgenerator.cli:cli
  skip: true  # [ppc64le]

requirements:
  build:
    - make  # [unix]
    - cmake >=3.27.0
    - ninja
    - toml  # [ppc64le]
    - tar  # [linux]
    - unzip  # [linux]
    - curl  # [linux]
    - zip  # [linux]
    - pkg-config  # [linux, osx]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python  # [build_platform != target_platform]
    - scikit-build-core  # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]

  host:
    - pip
    - python-build
    - ninja  # [win]
    - numpy
    - python
    - pybind11 >=2.10.0
    - scikit-build-core

  run:
    - numpy
    - click
    - python
    - {{ pin_compatible('libcxx', min_pin='x.x', max_pin='x.x') }}  # [osx]

test:
  imports:
    - sqsgenerator

about:
  home: https://github.com/dgehringer/sqsgenerator
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A command line tool written in Python/C++ to analyse short-range order or generate SQS structures

  description: |
    This package is a Special Quasirandom Structure generator written 
    in C++
  doc_url: https://sqsgenerator.readthedocs.io/en/latest
  dev_url: https://github.com/dgehringer/sqsgenerator

extra:
  recipe-maintainers:
    - jan-janssen
    - dgehringer
